"""
Django settings for spradar_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env in project root
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zi(k!398rrh8nk+s3ttvgqiogkm!xulxsl6yy49d=a*7w8^79c'

# Together AI API Key
TOGETHER_API_KEY = '07e297e19eaabe78c4ae52006f8d7ea67d6470727fff514aba20559fb273ea31'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Tüm hostlar (development için)
# Production'da: ['fxfutbol.com.tr', 'www.fxfutbol.com.tr', '167.71.74.229']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # django-allauth için gerekli
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS için
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # django-allauth için
]

ROOT_URLCONF = 'spradar_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'api' / 'templates'],  # ✅ Template klasörü eklendi
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spradar_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('ANALYTICS_DB_NAME', 'sr_analiz_db'),
        'USER': os.getenv('ANALYTICS_DB_USER', 'sport_user'),
        'PASSWORD': os.getenv('ANALYTICS_DB_PASSWORD', 'GucluSifre123!'),
        'HOST': os.getenv('ANALYTICS_DB_HOST', '167.71.74.229'),
        'PORT': os.getenv('ANALYTICS_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# EMAIL SETTINGS
# ==============================================================================

# Brevo (Sendinblue) SMTP kullanarak email gönderimi
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Production SMTP
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # Brevo SMTP Login: 9cb960001@smtp-brevo.com
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Brevo SMTP Key
EMAIL_TIMEOUT = 30  # 30 saniye timeout
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'FX Futbol <destek@fxfutbol.community>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Toplanan static dosyalar

# Static dosya klasörleri (opsiyonel - ek static dosyalar için)
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# REST FRAMEWORK SETTINGS
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# ==============================================================================
# CORS SETTINGS
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = True  # Development için
# Production'da bunu kapat ve CORS_ALLOWED_ORIGINS kullan


# ==============================================================================
# AUTHENTICATION SETTINGS
# ==============================================================================

# Django Sites Framework (allauth için gerekli)
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Django default
    'django.contrib.auth.backends.ModelBackend',
    
    # django-allauth
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Email ile giriş
ACCOUNT_EMAIL_REQUIRED = True  # Email zorunlu
ACCOUNT_USERNAME_REQUIRED = False  # Username opsiyonel
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Email doğrulama YOK (kullanıcı email girmek zorunda ama doğrulama maili gönderilmez)
ACCOUNT_UNIQUE_EMAIL = True  # Her email bir kez kullanılabilir
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Email doğrulandıktan sonra otomatik giriş

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Google ile otomatik kayıt
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Google zaten email doğruladı (Google için bypass)
SOCIALACCOUNT_QUERY_EMAIL = True  # Google'dan email iste
SOCIALACCOUNT_EMAIL_REQUIRED = True  # Google'dan email zorunlu
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGOUT_REDIRECT_URL = '/'

# HTTPS Settings (Production için - Nginx reverse proxy arkasında)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks (remember me için)
SESSION_SAVE_EVERY_REQUEST = False


# ==============================================================================
# CACHING SETTINGS (Optional - şimdilik kapalı)
# ==============================================================================

# Cache şimdilik kullanılmıyor
# Production'da Redis kullanılmalı!
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }


# ==============================================================================
# PAYMENT SETTINGS - Banka Bilgileri
# ==============================================================================

PAYMENT_BANK_ACCOUNTS = [
    {
        'bank_name': 'YAPI KREDİ',
        'iban': 'TR58 0006 7010 0000 0043 5680 59',
        'account_holder': 'AHMET YILDIRIR',
        'branch': 'YAPI KREDİ BANKASI',
    },
    {
        'bank_name': 'GARANTİ BANKASI',
        'iban': 'TR11 0006 2000 4560 0006 8704 99',
        'account_holder': 'AHMET YILDIRIR',
        'branch': 'GARANTİ BANKASI',
    }
]

# Ödeme talimatları
PAYMENT_INSTRUCTIONS = """
⚠️ ÖNEMLİ: Havale/EFT açıklama kısmına mutlaka ödeme kodunuzu yazın!
Örnek: KREDI-00123-AHMET

Ödeme kodunuzu yazmadan ödeme yaparsanız siparişiniz otomatik olarak eşleştirilemez.
"""
