# Generated by Django 5.2.8 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComprehensiveComebackAnalysis",
            fields=[
                ("match_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("season_id", models.IntegerField(blank=True, null=True)),
                ("match_date", models.CharField(blank=True, max_length=50, null=True)),
                ("home_team_id", models.IntegerField()),
                ("home_team_name", models.TextField()),
                ("away_team_id", models.IntegerField()),
                ("away_team_name", models.TextField()),
                ("home_matches_count", models.IntegerField(blank=True, null=True)),
                ("away_matches_count", models.IntegerField(blank=True, null=True)),
                ("home_comeback_score", models.FloatField(blank=True, null=True)),
                ("away_comeback_score", models.FloatField(blank=True, null=True)),
                ("combined_comeback_score", models.FloatField(blank=True, null=True)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("commentary_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "comprehensive_comeback_analysis",
                "ordering": ["-combined_comeback_score"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyMatchCommentary",
            fields=[
                ("match_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("match_date", models.CharField(max_length=50)),
                ("match_time", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("league", models.TextField(blank=True, null=True)),
                ("home_team_id", models.IntegerField()),
                ("home_team_name", models.TextField()),
                ("away_team_id", models.IntegerField()),
                ("away_team_name", models.TextField()),
                ("commentary_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_match_commentaries",
                "ordering": ["match_date", "match_time"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeagueComebackSummary",
            fields=[
                ("season_id", models.IntegerField(primary_key=True, serialize=False)),
                ("season_name", models.TextField(blank=True, null=True)),
                ("league_name", models.TextField(blank=True, null=True)),
                ("league_id", models.IntegerField(blank=True, null=True)),
                ("match_count", models.IntegerField(blank=True, null=True)),
                ("matches_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "league_comeback_summary",
                "ordering": ["-match_count"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MatchChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.BigIntegerField(db_index=True)),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "match_chat_history",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["match_id", "created_at"],
                        name="match_chat__match_i_66d1f0_idx",
                    )
                ],
            },
        ),
    ]
