# Generated by Django 5.2.8 on 2025-11-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Servis Adı"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("FIXTURE2X", "Fixture 2X"),
                            ("COMMENTARY", "Commentary"),
                            ("COMEBACK", "Comeback Analysis"),
                            ("SRSERVICE", "SR Service"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Servis Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "cron_schedule",
                    models.CharField(
                        blank=True,
                        help_text="Örn: 30 5 * * *",
                        max_length=50,
                        verbose_name="Cron Zamanı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Çalışma"
                    ),
                ),
                (
                    "last_status",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Son Durum"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
            ],
            options={
                "verbose_name": "Cron Servisi",
                "verbose_name_plural": "Cron Servisleri",
                "db_table": "cron_services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(max_length=200, verbose_name="İşlem Adı"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Başarılı"),
                            ("ERROR", "Hata"),
                            ("WARNING", "Uyarı"),
                            ("INFO", "Bilgi"),
                        ],
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Mesaj")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Detaylar"),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Süre (saniye)"
                    ),
                ),
                (
                    "processed_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="İşlenen Sayı"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hata Sayısı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Oluşturulma"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api.cronservice",
                        verbose_name="Servis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servis Logu",
                "verbose_name_plural": "Servis Logları",
                "db_table": "service_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "-created_at"],
                        name="service_log_service_82ce25_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="service_log_status_4e9203_idx",
                    ),
                ],
            },
        ),
    ]
