# Generated by Django 5.2.8 on 2025-11-27 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cronservice_servicelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('FREE', 'Ücretsiz (10 Kredi)'), ('GOLD', 'Gold (100 Kredi)'), ('PREMIUM', 'Premium (1.000 Kredi)'), ('PROFESSIONAL', 'Professional (10.000 Kredi)')], default='FREE', max_length=20, verbose_name='Üyelik Tipi')),
                ('credits', models.IntegerField(default=10, verbose_name='Kalan Kredi')),
                ('total_credits_earned', models.IntegerField(default=10, verbose_name='Toplam Kazanılan Kredi')),
                ('total_credits_used', models.IntegerField(default=0, verbose_name='Toplam Kullanılan Kredi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField(db_index=True, verbose_name='Maç ID')),
                ('match_info', models.CharField(blank=True, max_length=500, verbose_name='Maç Bilgisi')),
                ('user_question', models.TextField(verbose_name='Kullanıcı Sorusu')),
                ('ai_response', models.TextField(verbose_name='AI Cevabı')),
                ('credits_used', models.IntegerField(default=1, verbose_name='Kullanılan Kredi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_history', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yorum Geçmişi',
                'verbose_name_plural': 'Yorum Geçmişleri',
                'db_table': 'comment_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='comment_his_user_id_1ae85b_idx'), models.Index(fields=['match_id', '-created_at'], name='comment_his_match_i_db963c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Kredi Ekleme (+)'), ('DEBIT', 'Kredi Kullanma (-)')], max_length=10, verbose_name='İşlem Tipi')),
                ('amount', models.IntegerField(verbose_name='Miktar')),
                ('balance_after', models.IntegerField(verbose_name='İşlem Sonrası Bakiye')),
                ('reason', models.CharField(max_length=200, verbose_name='Sebep')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.userprofile', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kredi İşlemi',
                'verbose_name_plural': 'Kredi İşlemleri',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', '-created_at'], name='credit_tran_user_pr_fd6b1f_idx')],
            },
        ),
    ]
