# Generated by Django 5.2.8 on 2025-11-27 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_commenthistory_credittransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.IntegerField(verbose_name='Kredi Miktarı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('COMPLETED', 'Tamamlandı')], default='PENDING', max_length=20, verbose_name='Ödeme Durumu')),
                ('payment_note', models.TextField(blank=True, verbose_name='Ödeme Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan Admin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to='api.userprofile', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kredi Siparişi',
                'verbose_name_plural': 'Kredi Siparişleri',
                'db_table': 'credit_purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', '-created_at'], name='credit_purc_user_pr_1bedfe_idx'), models.Index(fields=['payment_status', '-created_at'], name='credit_purc_payment_4aad57_idx')],
            },
        ),
    ]
