# Generated by Django 5.2.8 on 2025-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_creditpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='payment_code',
            field=models.CharField(blank=True, db_index=True, help_text='Havale/EFT açıklamasına yazılacak benzersiz kod', max_length=50, verbose_name='Ödeme Kodu'),
        ),
    ]
