# Generated by Django 5.2.8 on 2025-11-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_creditpurchase_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='P2P kredi satışı yapabilir', verbose_name='Satıcı mı?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_account_holder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hesap Sahibi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banka Adı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_completed_orders',
            field=models.IntegerField(default=0, help_text='Onaylanan sipariş sayısı', verbose_name='Tamamlanan Sipariş'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_is_active',
            field=models.BooleanField(default=True, help_text='Listeye çıksın mı?', verbose_name='Satıcı Aktif mi?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_price',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text="Supervisor kredilerini bu fiyattan satar (Admin 0.29 TL'ye satar)", max_digits=6, verbose_name='Satış Fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_total_orders',
            field=models.IntegerField(default=0, help_text='Alınan toplam sipariş sayısı', verbose_name='Toplam Sipariş'),
        ),
        migrations.CreateModel(
            name='SupervisorCreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.IntegerField(verbose_name='Kredi Miktarı')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="Supervisor'un belirlediği kredi başına fiyat", max_digits=6, verbose_name='Birim Fiyat (TL)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat (TL)')),
                ('payment_code', models.CharField(blank=True, db_index=True, help_text='Havale/EFT açıklamasına yazılacak kod', max_length=50, verbose_name='Ödeme Kodu')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Ödeme Durumu')),
                ('payment_note', models.TextField(blank=True, verbose_name='Ödeme Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('supervisor_note', models.TextField(blank=True, verbose_name='Supervisor Notu')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_purchases', to='api.userprofile', verbose_name='Alıcı Kullanıcı')),
                ('supervisor', models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_sales', to='api.userprofile', verbose_name='Satıcı (Supervisor)')),
            ],
            options={
                'verbose_name': 'Supervisor Kredi Siparişi',
                'verbose_name_plural': 'Supervisor Kredi Siparişleri',
                'db_table': 'supervisor_credit_purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='supervisor__buyer_i_dc2996_idx'), models.Index(fields=['supervisor', '-created_at'], name='supervisor__supervi_e7a2bd_idx'), models.Index(fields=['payment_status', '-created_at'], name='supervisor__payment_4c725e_idx')],
            },
        ),
    ]
