# Generated by Django 5.2.8 on 2025-11-27 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_is_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banka Adı')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Hesap Sahibi')),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0.35, help_text='Kredilerinizi kaça satmak istiyorsunuz?', max_digits=6, verbose_name='Önerilen Satış Fiyatı (TL/kredi)')),
                ('description', models.TextField(blank=True, help_text='Neden satıcı olmak istiyorsunuz? (İsteğe bağlı)', verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Başvuru Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen Admin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_applications', to='api.userprofile', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Supervisor Başvurusu',
                'verbose_name_plural': 'Supervisor Başvuruları',
                'db_table': 'supervisor_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', '-created_at'], name='supervisor__user_pr_fe8820_idx'), models.Index(fields=['status', '-created_at'], name='supervisor__status_4d9a33_idx')],
            },
        ),
    ]
