# Generated by Django 5.2.8 on 2025-11-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_supervisorapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Kredi Miktarı")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Not"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Transfer Tarihi"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transfers",
                        to="api.userprofile",
                        verbose_name="Gönderen",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transfers",
                        to="api.userprofile",
                        verbose_name="Alıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kredi Transferi",
                "verbose_name_plural": "Kredi Transferleri",
                "db_table": "credit_transfers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "-created_at"],
                        name="credit_tran_from_us_424ea3_idx",
                    ),
                    models.Index(
                        fields=["to_user", "-created_at"],
                        name="credit_tran_to_user_c0ce29_idx",
                    ),
                ],
            },
        ),
    ]
