# Generated by Django 5.2.8 on 2025-11-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_credittransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('announcement_type', models.CharField(choices=[('INFO', 'Bilgi'), ('SUCCESS', 'Başarı'), ('WARNING', 'Uyarı'), ('DANGER', 'Önemli')], default='INFO', max_length=20, verbose_name='Tip')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Sabitle (Üstte Göster)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('category', models.CharField(choices=[('GENERAL', 'Genel Soru'), ('TECHNICAL', 'Teknik Sorun'), ('PAYMENT', 'Ödeme/Kredi'), ('SUPERVISOR', 'Supervisor Başvuru'), ('FEEDBACK', 'Öneri/Geri Bildirim'), ('OTHER', 'Diğer')], default='GENERAL', max_length=20, verbose_name='Kategori')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('IN_PROGRESS', 'Cevaplanıyor'), ('CLOSED', 'Kapatıldı')], default='OPEN', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='MEDIUM', max_length=20, verbose_name='Öncelik')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Admin Cevabı')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Cevaplanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Okunma Tarihi')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='api.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Okunmuş Duyuru',
                'verbose_name_plural': 'Okunmuş Duyurular',
                'db_table': 'user_announcement_reads',
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
