# Generated by Django 5.2.8 on 2025-11-27 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_old_chat_messages(apps, schema_editor):
    """
    Eski user'sız mesajları temizle.
    Artık her mesaj bir kullanıcıya bağlı olmalı.
    """
    MatchChatHistory = apps.get_model('api', 'MatchChatHistory')
    deleted_count = MatchChatHistory.objects.filter(user__isnull=True).count()
    MatchChatHistory.objects.filter(user__isnull=True).delete()
    print(f"✅ {deleted_count} adet eski chat mesajı temizlendi (user'sız mesajlar)")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_announcement_supportticket_userannouncementread"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="matchchathistory",
            name="match_chat__match_i_66d1f0_idx",
        ),
        migrations.AddField(
            model_name="matchchathistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="matchchathistory",
            index=models.Index(
                fields=["match_id", "user", "created_at"],
                name="match_chat__match_i_dd488b_idx",
            ),
        ),
        migrations.RunPython(cleanup_old_chat_messages, migrations.RunPython.noop),
    ]
